name: Gradle Precommit
on: [pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Run Gradle
        run: |
          ./gradlew precommit --parallel
